In [1]:
import torch
import numpy as np

In [2]:
data = [[1,2], [3,4]]
x_data = torch.tensor(data)

In [3]:
x_data

tensor([[1, 2],
        [3, 4]])

In [4]:
np_array = np.array(data)
x_np = torch.from_numpy(np_array)

In [5]:
x_np

tensor([[1, 2],
        [3, 4]])

In [7]:
tensor = torch.rand(3,4)

print(tensor.shape)
print(tensor.dtype)
print(tensor.device)

torch.Size([3, 4])
torch.float32
cpu


In [8]:
if torch.cuda.is_available():
    tensor = tensor.to("cuda")

In [9]:
y1 = tensor @ tensor.T
y2 = tensor.matmul(tensor.T)

In [11]:
print(y1)
print(y2)

tensor([[0.6612, 0.4828, 1.0315],
        [0.4828, 0.7777, 0.9823],
        [1.0315, 0.9823, 1.7943]], device='cuda:0')
tensor([[0.6612, 0.4828, 1.0315],
        [0.4828, 0.7777, 0.9823],
        [1.0315, 0.9823, 1.7943]], device='cuda:0')


In [13]:
print(tensor)
print(tensor * tensor)

tensor([[0.3626, 0.3342, 0.3670, 0.5323],
        [0.2241, 0.8311, 0.0986, 0.1645],
        [0.6702, 0.8210, 0.6135, 0.5429]], device='cuda:0')
tensor([[0.1314, 0.1117, 0.1347, 0.2834],
        [0.0502, 0.6907, 0.0097, 0.0271],
        [0.4491, 0.6740, 0.3764, 0.2947]], device='cuda:0')
